# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 JoshKirk800
"""Output formats for a finished design (a generated_insoles/vNN folder).

    export(fmt, version_dir, out_dir) -> [written file paths]

bambu   Bambu Studio 3MF (native: two plates, zones and settings embedded)
orca    the same 3MF for OrcaSlicer, which reads Bambu Studio projects
prusa   PrusaSlicer 3MF, one file per foot (single bed): body + infill modifier volumes, its own config keys
stl     insole and zone STLs + a settings sheet and zone map, to set up by hand in any slicer (Cura, ...)
"""
import glob
import json
import os
import re
import shutil
import zipfile

import numpy as np
import trimesh

import generate_clean_bambu_project as g3mf

PRUSA_KEYS = {"sparse_infill_density": "fill_density", "top_shell_layers": "top_solid_layers", "bottom_shell_layers": "bottom_solid_layers"}


def load_design(version_dir):
    return json.load(open(os.path.join(version_dir, "design.json")))


def zone_files(version_dir, side, design=None):
    """[(path, name, density %)] of the infill-zone STLs of one foot, in file order (names from design.json)."""
    design = design or load_design(version_dir)
    names = [z.rsplit(": ", 1)[0] for z in design["plans"][side]["result"]["zones"]]
    out = []
    for i, f in enumerate(sorted(glob.glob(os.path.join(version_dir, f"{side}_zone_*.stl")))):
        out.append((f, names[i] if i < len(names) else os.path.basename(f), int(re.search(r"_(\d+)pct", f).group(1))))
    return out


def _copy(version_dir, names, out_dir):
    os.makedirs(out_dir, exist_ok=True)
    written = []
    for n in names:
        src = os.path.join(version_dir, n)
        if os.path.exists(src):
            shutil.copy2(src, out_dir)
            written.append(os.path.join(out_dir, n))
    return written


# ── Bambu Studio / OrcaSlicer ──────────────────────────────────────────────────
BAMBU_FILES = ("Custom_Insoles_ME3D.3mf", "test_coupons.3mf", "test_coupons.json", "design.json", "preview.png")


def export_bambu(version_dir, out_dir):
    return _copy(version_dir, BAMBU_FILES, out_dir)


def export_orca(version_dir, out_dir):
    return _copy(version_dir, BAMBU_FILES, out_dir)


# ── PrusaSlicer ────────────────────────────────────────────────────────────────
def _mesh_xml(vertices, triangles):
    v = "\n".join(f'    <vertex x="{p[0]:.4f}" y="{p[1]:.4f}" z="{p[2]:.4f}"/>' for p in vertices)
    t = "\n".join(f'    <triangle v1="{f[0]}" v2="{f[1]}" v3="{f[2]}"/>' for f in triangles)
    return f"   <mesh>\n    <vertices>\n{v}\n    </vertices>\n    <triangles>\n{t}\n    </triangles>\n   </mesh>"


def prusa_config(process):
    """Metadata/Slic3r_PE.config lines for the project: PrusaSlicer's own keys (our Bambu keys translated)."""
    cfg = {"layer_height": g3mf.LAYER_HEIGHT, "first_layer_height": g3mf.LAYER_HEIGHT, "perimeters": g3mf.WALL_LOOPS,
           "fill_pattern": "gyroid", "filament_type": "FLEX", "filament_diameter": "1.75", "nozzle_diameter": "0.4",
           "filament_max_volumetric_speed": g3mf.MAX_VOLUMETRIC_SPEED, "bed_shape": f"0x0,{g3mf.BED:g}x0,{g3mf.BED:g}x{g3mf.BED:g},0x{g3mf.BED:g}"}
    for k, v in process.items():
        if k in PRUSA_KEYS:
            cfg[PRUSA_KEYS[k]] = v
    if process.get("enable_support") == "1":     # arch-pocket roof: organic supports from the plate only
        cfg.update({"support_material": "1", "support_material_auto": "1", "support_material_buildplate_only": "1",
                    "support_material_style": "organic", "support_material_contact_distance": process.get("support_top_z_distance", "0.3")})
    return "; generated by insole-pipeline for PrusaSlicer\n\n" + "".join(f"; {k} = {v}\n" for k, v in sorted(cfg.items()))


def write_prusa_3mf(name, body_stl, zones, process, out_path):
    """One object = body mesh + modifier meshes concatenated; Slic3r_PE_model.config gives each volume's triangle range,
    its type and (for modifiers) its infill. The object is rotated 45 deg and centred on a 256 mm bed, like the Bambu plates."""
    body = trimesh.load(body_stl)
    volumes = [("Insole", "ModelPart", body, {})] + [
        (zname, "ParameterModifier", trimesh.load(path), {"fill_density": f"{dens}%", "fill_pattern": "gyroid"}) for path, zname, dens in zones]
    verts, tris, ranges, v0, t0 = [], [], [], 0, 0
    for _, _, mesh, _ in volumes:
        verts.append(mesh.vertices)
        tris.append(mesh.faces + v0)
        ranges.append((t0, t0 + len(mesh.faces) - 1))
        v0, t0 = v0 + len(mesh.vertices), t0 + len(mesh.faces)
    tx, ty, tz = g3mf._placement(body, 0)
    model = (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<model unit="millimeter" xml:lang="en-US" xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02" xmlns:slic3rpe="http://schemas.slic3r.org/3mf/2017/06">\n'
        ' <metadata name="slic3rpe:Version3mf">1</metadata>\n'
        ' <resources>\n  <object id="1" type="model">\n' + _mesh_xml(np.vstack(verts), np.vstack(tris)) + '\n  </object>\n </resources>\n'
        f' <build>\n  <item objectid="1" transform="{g3mf.C:.6f} {g3mf.S:.6f} 0 {-g3mf.S:.6f} {g3mf.C:.6f} 0 0 0 1 {tx:.4f} {ty:.4f} {tz:.4f}" printable="1"/>\n </build>\n'
        '</model>')
    ident = "1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1"
    vol_xml = ""
    for (vname, vtype, _, cfg), (a, b) in zip(volumes, ranges):
        meta = lambda key, val: f'   <metadata type="volume" key="{key}" value="{val}"/>\n'
        vol_xml += (f'  <volume firstid="{a}" lastid="{b}">\n' + meta("name", vname) + (meta("modifier", "1") if vtype == "ParameterModifier" else "")
                    + meta("volume_type", vtype) + meta("matrix", ident) + "".join(meta(k, v) for k, v in cfg.items()) + "  </volume>\n")
    model_cfg = ('<?xml version="1.0" encoding="UTF-8"?>\n<config>\n <object id="1" instances_count="1">\n'
                 f'  <metadata type="object" key="name" value="{name}"/>\n' + vol_xml + ' </object>\n</config>\n')
    content_types = ('<?xml version="1.0" encoding="UTF-8"?>\n<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">\n'
                     ' <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>\n'
                     ' <Default Extension="model" ContentType="application/vnd.ms-package.3dmanufacturing-3dmodel+xml"/>\n</Types>')
    rels = ('<?xml version="1.0" encoding="UTF-8"?>\n<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">\n'
            ' <Relationship Target="/3D/3dmodel.model" Id="rel-1" Type="http://schemas.microsoft.com/3dmanufacturing/2013/01/3dmodel"/>\n</Relationships>')
    with zipfile.ZipFile(out_path, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("[Content_Types].xml", content_types)
        zf.writestr("_rels/.rels", rels)
        zf.writestr("3D/3dmodel.model", model)
        zf.writestr("Metadata/Slic3r_PE.config", prusa_config(process))
        zf.writestr("Metadata/Slic3r_PE_model.config", model_cfg)


def export_prusa(version_dir, out_dir):
    os.makedirs(out_dir, exist_ok=True)
    design = load_design(version_dir)
    written = []
    for side in ("left", "right"):
        path = os.path.join(out_dir, f"{side}_insole_prusaslicer.3mf")
        write_prusa_3mf(f"{side.capitalize()} insole", os.path.join(version_dir, f"{side}_insole.stl"), zone_files(version_dir, side, design),
                        design["process"], path)
        written.append(path)
    return written + _copy(version_dir, ("design.json", "preview.png"), out_dir)


# ── STL + settings sheet (any slicer) ──────────────────────────────────────────
def settings_sheet(design, zones):
    p, plans = design["process"], design["plans"]
    lines = [
        "# Slicer setup (manual)", "",
        "Print each insole as one object. Add every zone STL as an infill **modifier** (not a part) and give it the density",
        "below. All STLs share the insole's coordinate frame; if your slicer re-centres a loaded modifier, place it using",
        "`zone_map.png`.", "",
        "## Whole object", "",
        f"- Material: 95A TPU (Bambu TPU 95A HF), 0.4 mm nozzle, textured PEI plate with glue stick, max volumetric speed {g3mf.MAX_VOLUMETRIC_SPEED} mm3/s",
        f"- Layer height {g3mf.LAYER_HEIGHT} mm, {g3mf.WALL_LOOPS} wall loops, {p['top_shell_layers']} top / {p['bottom_shell_layers']} bottom solid layers",
        f"- Sparse infill {p['sparse_infill_density']} gyroid", "",
    ]
    if p.get("enable_support") == "1":
        lines += [f"- Supports: tree/organic, build plate only, {p.get('support_top_z_distance', '0.3')} mm top gap (the arch pocket roof overhangs)", ""]
    for side in ("left", "right"):
        lines += [f"## {side.capitalize()} insole ({plans[side]['label']})", "", f"Object: `{side}_insole.stl`", ""]
        if zones[side]:
            lines += ["| modifier STL | zone | infill |", "|---|---|---|"] + [f"| `{os.path.basename(f)}` | {n} | {d}% gyroid |" for f, n, d in zones[side]] + [""]
        else:
            lines += ["No infill zones: base infill everywhere.", ""]
    lines += ["## Per slicer", "",
              "- **PrusaSlicer**: right-click the object > Add modifier > Load..., then set Infill > Fill density and pattern on it.",
              "- **Cura**: load the zone STL, Per Model Settings > Modify settings for overlaps > Infill mesh only, add Infill Density and Infill Pattern.",
              "- Bambu Studio / OrcaSlicer: use the 3MF formats instead (everything is embedded).", ""]
    return "\n".join(lines)


def zone_map(version_dir, zones, path):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from pressure_maps import insole_outline, zone_footprints
    fig, axes = plt.subplots(1, 2, figsize=(10, 10))
    cmap = plt.cm.viridis
    for ax, side in zip(axes, ("left", "right")):
        ax.plot(*insole_outline(version_dir, side).exterior.xy, color="k", lw=1.2)
        for k, (f, name, dens) in enumerate(zones[side]):
            poly = [p for fn, d, p in zone_footprints(version_dir, side) if fn == os.path.basename(f)][0]
            for part in getattr(poly, "geoms", [poly]):
                ax.fill(*part.exterior.xy, color=cmap((dens - 10) / 30), alpha=0.5, ec="k", lw=0.5)
            c = poly.representative_point()
            ax.text(c.x, c.y, f"{k + 1:02d}\n{dens}%", ha="center", va="center", fontsize=7)
        ax.set_aspect("equal")
        ax.set_title(f"{side}: zone files NN_<pct>pct, heel at bottom", fontsize=9)
    plt.tight_layout()
    plt.savefig(path, dpi=90)
    plt.close(fig)


def export_stl(version_dir, out_dir):
    os.makedirs(out_dir, exist_ok=True)
    design = load_design(version_dir)
    zones = {s: zone_files(version_dir, s, design) for s in ("left", "right")}
    written = _copy(version_dir, ["left_insole.stl", "right_insole.stl"] + [os.path.basename(f) for s in zones for f, _, _ in zones[s]], out_dir)
    sheet = os.path.join(out_dir, "slicer_settings.md")
    open(sheet, "w", encoding="utf-8").write(settings_sheet(design, zones))
    js = os.path.join(out_dir, "slicer_settings.json")
    json.dump({"process": design["process"], "layer_height": g3mf.LAYER_HEIGHT, "wall_loops": g3mf.WALL_LOOPS,
               "feet": {s: {"insole": f"{s}_insole.stl", "zones": [{"file": os.path.basename(f), "name": n, "density_pct": d, "pattern": "gyroid"}
                                                                  for f, n, d in zones[s]]} for s in zones}}, open(js, "w"), indent=2)
    zm = os.path.join(out_dir, "zone_map.png")
    zone_map(version_dir, zones, zm)
    return written + [sheet, js, zm]


FORMATS = {
    "bambu": ("Bambu Studio 3MF", "native: two plates, zones and all settings embedded", export_bambu),
    "orca": ("OrcaSlicer 3MF", "the same file; Orca reads Bambu Studio projects (not tested here)", export_orca),
    "prusa": ("PrusaSlicer 3MF", "one file per foot, modifiers + settings in PrusaSlicer's own keys", export_prusa),
    "stl": ("STL files + settings sheet", "any other slicer (Cura, ...): set the zones up by hand", export_stl),
}


def export(fmt, version_dir, out_dir):
    return FORMATS[fmt][2](version_dir, out_dir)
